spring:
  security:
    oauth2:
      client:
        registration:
          meus-contatos:
            authorization-grant-type: client_credentials
            client-id: cli-cred-client
            client-secret: wqXKbLI0KE8yMAHr2wcafZzyOaPCfdP5
            scope: contatos:read
          gestao-funcionarios:
            authorization-grant-type: client_credentials
            client-id: realocacao-squad-client
            client-secret: 7GQb6X8Gqt7EtNpYg8INbhGFgJG2WE3Y
            scope: funcionarios:read
          livraria:
            authorization-grant-type: client_credentials
            client-id: exposicao-livros-client
            client-secret: wEcSpxbQj2cjTt8q6Od6uQzV8LbxPEPH
            scope: [livros:read, autores:read]
        provider:
          meus-contatos:
            token-uri: http://localhost:18080/realms/meus-contatos/protocol/openid-connect/token
          gestao-funcionarios:
            token-uri: http://localhost:18080/realms/gestao-funcionarios/protocol/openid-connect/token
          livraria:
            token-uri: http://localhost:18080/realms/livraria/protocol/openid-connect/token
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8081
  error:
    include-message: always
    include-exception: false
    include-stacktrace: on-param
    include-binding-errors: always

logging:
  level:
    '[org.springframework.web.client]': DEBUG
    '[org.springframework.web.reactive.function.client]': DEBUG
    '[reactor.netty.http.client]': DEBUG
